/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.bluefoxsoftware.bluefoxcardgames

import com.googlecode.lanterna.terminal.*
import com.googlecode.lanterna.screen.*

fun main() {
    val screen = TerminalScreen(DefaultTerminalFactory().createTerminal())

    screen.startScreen()

    screen.readInput()

    screen.stopScreen()
}
